server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    
    # Aumentar limite de upload para não barrar as fotos (padrão é 1MB)
    client_max_body_size 20M;

    # Proxy Reverso: Envia tudo que começar com /api para o Spring Boot
    location /api/ {
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Essa configuração é crucial para o React Router (SPA)
    # Sempre que não achar um arquivo, devolve o index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
