name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

      - name: Compactar Arquivos localmente
        run: tar -czf app.tar.gz --exclude=node_modules --exclude=target --exclude=.git --exclude=dist *

      - name: Enviar pacote via SCP Nativamente
        run: scp -v -i ~/.ssh/id_rsa app.tar.gz ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }}:/home/ubuntu/

      - name: Descompactar e Fazer Deploy
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} << 'EOF'
            mkdir -p storePriceTrack
            tar -xzf app.tar.gz -C storePriceTrack
            cd storePriceTrack
            sudo docker compose --env-file backend/.env up -d --build
          EOF
