name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: cd backend && mvn clean package -Dmaven.test.skip=true

      - name: Configurar Chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Compactar Arquivos localmente
        run: tar -czf app.tar.gz --exclude=node_modules --exclude=.git --exclude=dist *

      - name: Enviar pacote via SCP Nativamente
        run: scp -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa app.tar.gz ubuntu@54.233.118.144:/home/ubuntu/

      - name: Descompactar e Fazer Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@54.233.118.144 << 'EOF'
            mkdir -p storePriceTrack
            tar -xzf app.tar.gz -C storePriceTrack
            cd storePriceTrack
            sudo docker compose --env-file backend/.env up -d --build
          EOF
