name: Rescue SSH Key

on:
  push:
    branches:
      - master

jobs:
  rescue:
    runs-on: ubuntu-latest
    steps:
      - name: Criar Arquivo
        run: echo "${{ secrets.AWS_SSH_KEY }}" > awsCloud.pem
        
      - name: Disponibilizar para Download
        uses: actions/upload-artifact@v4
        with:
          name: awsCloud-resgatada
          path: awsCloud.pem
